services:

  proxy:
    image: traefik:3.0
    restart: always
    ports:
      - "80:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
    networks:
      - traefik-public
      - default

  db:
    image: postgres:15
    restart: always
    ports:
      - "8085:8080"


  adminer:
    image: adminer
    restart: always
    ports:
      - "8086:8080"

  czfb:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    command:
      - /app/.venv/bin/uvicorn
      - swx_api.core.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
    volumes:
      - ./swx_api:/app/swx_api
      - ./pyproject.toml:/app/pyproject.toml
      - ./migrations:/app/migrations
    develop:
      watch:
        - path: ./swx_api
          action: sync
          target: /app/swx_api
          ignore:
            - .venv
        - path: pyproject.toml
          action: rebuild
          target: /app/pyproject.toml


volumes:
  app-db-data:

networks:
  traefik-public:
    external: false
