"""Add audit_log table

Revision ID: 325a7c535a18
Revises: add_rbac_admin_user
Create Date: 2026-01-25 17:09:24.311076

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "325a7c535a18"
down_revision = 'add_rbac_admin_user'
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration changes.

    Add or modify database structures here.

    Example:
    op.add_column("users", sa.Column("new_column", sa.String(length=255), nullable=True))
    op.create_index("ix_users_new_column", "users", ["new_column"])
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_type'), 'audit_log', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_log_outcome'), 'audit_log', ['outcome'], unique=False)
    op.create_index(op.f('ix_audit_log_request_id'), 'audit_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.alter_column('admin_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_user', 'auth_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('admin_user_email_key'), 'admin_user', type_='unique')
    op.drop_index(op.f('ix_admin_user_provider_id'), table_name='admin_user')
    op.alter_column('permission', 'description',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('permission_name_key'), 'permission', type_='unique')
    op.drop_column('permission', 'created_at')
    op.drop_column('permission', 'updated_at')
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('role', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('role', 'domain',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('role_name_key'), 'role', type_='unique')
    op.drop_column('role', 'created_at')
    op.drop_column('role', 'updated_at')
    op.drop_constraint(op.f('uq_role_permission'), 'role_permission', type_='unique')
    op.drop_constraint(op.f('role_permission_role_id_fkey'), 'role_permission', type_='foreignkey')
    op.drop_constraint(op.f('role_permission_permission_id_fkey'), 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'])
    op.drop_column('role_permission', 'created_at')
    op.drop_column('role_permission', 'updated_at')
    op.drop_column('team', 'created_at')
    op.drop_column('team', 'updated_at')
    op.drop_constraint(op.f('uq_team_member'), 'team_member', type_='unique')
    op.drop_constraint(op.f('team_member_team_id_fkey'), 'team_member', type_='foreignkey')
    op.drop_constraint(op.f('team_member_role_id_fkey'), 'team_member', type_='foreignkey')
    op.drop_constraint(op.f('team_member_user_id_fkey'), 'team_member', type_='foreignkey')
    op.create_foreign_key(None, 'team_member', 'team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'team_member', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'team_member', 'users', ['user_id'], ['id'])
    op.drop_column('team_member', 'created_at')
    op.drop_column('team_member', 'updated_at')
    op.create_index(op.f('ix_user_role_resource_id'), 'user_role', ['resource_id'], unique=False)
    op.drop_constraint(op.f('user_role_role_id_fkey'), 'user_role', type_='foreignkey')
    op.drop_constraint(op.f('user_role_user_id_fkey'), 'user_role', type_='foreignkey')
    op.drop_constraint(op.f('user_role_team_id_fkey'), 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_role', 'team', ['team_id'], ['id'])
    op.drop_column('user_role', 'created_at')
    op.drop_column('user_role', 'updated_at')
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.drop_constraint(op.f('users_identifier_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'metadata')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'identifier')
    # ### end Alembic commands ###


def downgrade():
    """Rollback migration changes.

    Undo changes made in upgrade().

    Example:
    op.drop_index("ix_users_new_column", table_name="users")
    op.drop_column("users", "new_column")
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('createdAt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_identifier_key'), 'users', ['identifier'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=True)
    op.add_column('user_role', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_role', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_team_id_fkey'), 'user_role', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_role_user_id_fkey'), 'user_role', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_role_role_id_fkey'), 'user_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_role_resource_id'), table_name='user_role')
    op.add_column('team_member', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('team_member', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.create_foreign_key(op.f('team_member_user_id_fkey'), 'team_member', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('team_member_role_id_fkey'), 'team_member', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('team_member_team_id_fkey'), 'team_member', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_team_member'), 'team_member', ['team_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.add_column('team', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('team', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role_permission', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role_permission', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_permission_id_fkey'), 'role_permission', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permission_role_id_fkey'), 'role_permission', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_role_permission'), 'role_permission', ['role_id', 'permission_id'], postgresql_nulls_not_distinct=False)
    op.add_column('role', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('role_name_key'), 'role', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('role', 'domain',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               nullable=False)
    op.alter_column('role', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('role', 'description',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.add_column('permission', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('permission', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('permission_name_key'), 'permission', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('permission', 'description',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_admin_user_provider_id'), 'admin_user', ['provider_id'], unique=True)
    op.create_unique_constraint(op.f('admin_user_email_key'), 'admin_user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('admin_user', 'auth_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'local'::character varying"),
               existing_nullable=False)
    op.alter_column('admin_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_request_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_outcome'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
