"""Add billing tables

Revision ID: 8d6de0d76cce
Revises: 325a7c535a18
Create Date: 2026-01-25 18:34:25.716595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = "8d6de0d76cce"
down_revision = '325a7c535a18'
branch_labels = None
depends_on = None


def upgrade():
    """Apply migration changes.

    Add or modify database structures here.

    Example:
    op.add_column("users", sa.Column("new_column", sa.String(length=255), nullable=True))
    op.create_index("ix_users_new_column", "users", ["new_column"])
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_type', sa.Enum('USER', 'TEAM', 'ORGANIZATION', name='billingaccounttype'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('billing_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_account_account_type'), 'billing_account', ['account_type'], unique=False)
    op.create_index(op.f('ix_billing_account_owner_id'), 'billing_account', ['owner_id'], unique=False)
    op.create_index(op.f('ix_billing_account_stripe_customer_id'), 'billing_account', ['stripe_customer_id'], unique=True)
    op.create_table('billing_feature',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feature_type', sa.Enum('BOOLEAN', 'QUOTA', 'METERED', name='featuretype'), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_feature_key'), 'billing_feature', ['key'], unique=True)
    op.create_table('billing_plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_plan_is_active'), 'billing_plan', ['is_active'], unique=False)
    op.create_index(op.f('ix_billing_plan_key'), 'billing_plan', ['key'], unique=True)
    op.create_table('billing_plan_entitlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['billing_feature.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_plan_entitlement_feature_id'), 'billing_plan_entitlement', ['feature_id'], unique=False)
    op.create_index(op.f('ix_billing_plan_entitlement_plan_id'), 'billing_plan_entitlement', ['plan_id'], unique=False)
    op.create_table('billing_subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['billing_account.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscription_account_id'), 'billing_subscription', ['account_id'], unique=False)
    op.create_index(op.f('ix_billing_subscription_plan_id'), 'billing_subscription', ['plan_id'], unique=False)
    op.create_index(op.f('ix_billing_subscription_status'), 'billing_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_billing_subscription_stripe_subscription_id'), 'billing_subscription', ['stripe_subscription_id'], unique=True)
    op.create_table('billing_usage_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['billing_account.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['billing_feature.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_usage_record_account_id'), 'billing_usage_record', ['account_id'], unique=False)
    op.create_index(op.f('ix_billing_usage_record_feature_id'), 'billing_usage_record', ['feature_id'], unique=False)
    op.create_index(op.f('ix_billing_usage_record_period_end'), 'billing_usage_record', ['period_end'], unique=False)
    op.create_index(op.f('ix_billing_usage_record_period_start'), 'billing_usage_record', ['period_start'], unique=False)
    op.create_index(op.f('ix_billing_usage_record_subscription_id'), 'billing_usage_record', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    """Rollback migration changes.

    Undo changes made in upgrade().

    Example:
    op.drop_index("ix_users_new_column", table_name="users")
    op.drop_column("users", "new_column")
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_usage_record_subscription_id'), table_name='billing_usage_record')
    op.drop_index(op.f('ix_billing_usage_record_period_start'), table_name='billing_usage_record')
    op.drop_index(op.f('ix_billing_usage_record_period_end'), table_name='billing_usage_record')
    op.drop_index(op.f('ix_billing_usage_record_feature_id'), table_name='billing_usage_record')
    op.drop_index(op.f('ix_billing_usage_record_account_id'), table_name='billing_usage_record')
    op.drop_table('billing_usage_record')
    op.drop_index(op.f('ix_billing_subscription_stripe_subscription_id'), table_name='billing_subscription')
    op.drop_index(op.f('ix_billing_subscription_status'), table_name='billing_subscription')
    op.drop_index(op.f('ix_billing_subscription_plan_id'), table_name='billing_subscription')
    op.drop_index(op.f('ix_billing_subscription_account_id'), table_name='billing_subscription')
    op.drop_table('billing_subscription')
    op.drop_index(op.f('ix_billing_plan_entitlement_plan_id'), table_name='billing_plan_entitlement')
    op.drop_index(op.f('ix_billing_plan_entitlement_feature_id'), table_name='billing_plan_entitlement')
    op.drop_table('billing_plan_entitlement')
    op.drop_index(op.f('ix_billing_plan_key'), table_name='billing_plan')
    op.drop_index(op.f('ix_billing_plan_is_active'), table_name='billing_plan')
    op.drop_table('billing_plan')
    op.drop_index(op.f('ix_billing_feature_key'), table_name='billing_feature')
    op.drop_table('billing_feature')
    op.drop_index(op.f('ix_billing_account_stripe_customer_id'), table_name='billing_account')
    op.drop_index(op.f('ix_billing_account_owner_id'), table_name='billing_account')
    op.drop_index(op.f('ix_billing_account_account_type'), table_name='billing_account')
    op.drop_table('billing_account')
    # ### end Alembic commands ###
